# Generated by Django 5.1.6 on 2025-05-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game',
            field=models.CharField(max_length=20),
        ),
    ]
